linters:
  enable-all: true
  disable:
    - exhaustivestruct
    - exhaustruct
    - gci
    - gochecknoglobals
    - goerr113
    - gofumpt
    - ireturn
    - nlreturn
    - noctx
    - nosnakecase
    - varnamelen

issues:
  exclude-rules:
    - path: internal/scraper/test/scraper.go
      linters:
        - funlen
    - path: _test\.go
      linters:
        - cyclop
        - funlen
        - lll
        - paralleltest
        - scopelint
    - path: doc\.go
      linters:
        - lll
